config/routes.rb
Shoutbox::Application.routes.draw do
  resources :shouts, :only => [:new, :create, :edit, :update, :destroy, :index] do
    resources :comments, :only => [:new, :create]
  end
  root :to => "shouts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/shout.rb
class Shout <ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :body
  
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @shout   = Shout.find(params[:shout_id])
    @comment = Comment.new
  end
  
  def create
    @shout   = Shout.find(params[:shout_id])
    @comment = @shout.comments.new(params[:comment])
    if @comment.save
      flash[:notice] = "Comment has been created."
      redirect_to shouts_path
    else
      render :new
    end
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def new
    @shout = Shout.new
  end
  
  def create
    @shout = Shout.new(params[:shout])
    if @shout.save
      flash[:notice] = "Shout has been created."
#       redirect_to shouts_url
      redirect_to :action => :index
    else
      render :new   
    end
  end
  
  def edit
    @shout = Shout.find(params[:id])
  end
  
  def update
    @shout = Shout.update(params[:id], params[:shout])
      flash[:notice] = "Shout has been updated!"
#       redirect_to shouts_url
      redirect_to :action => :index
  end
  
  def destroy
    @shout = Shout.destroy(params[:id])
      flash[:notice] = "Shout has been deleted!"
  #       redirect_to shouts_url
      redirect_to :action => :index
  end
  
  def index
    @shouts = Shout.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<div id="new-comment">
  <div>
    <li>
      <strong>Name:</strong> <%= @shout.name %>
    </li>
    <li>
      <b>Body:</b> <%= @shout.body %>
    </li>
  </div>

  <div>
    <%= form_for [@shout, @comment] do |form| %>
      <%= form.error_messages %>
      <p>
        <%= form.label     :body %>
        <%= form.text_area :body %>  
      </p>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoutbox</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  
<%= link_to (root_url) do %>
<div id="heading">
<h1>Shoutbox</h1>
</div>
<% end %>

<div id="flash">
 <% flash.each do |key,value| -%>
   <div id="flash_<%= key %>"><%=h value %></div>
 <% end -%>
</div>
<%= yield %>

</body>
</html>

app/views/shouts/edit.html.erb
<div id="shout-form">
  <%= form_for @shout do |form| %>
    <%= form.error_messages %>
    <p>
      <%= form.label      :name %>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label     :body %>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit "Update" %>
    </p>  
  <% end %>
</div>

app/views/shouts/index.html.erb
<div id="shout-list">
<% @shouts.each do |s| %>
  <ul>
    <li>
     <strong>Name:</strong> <%= s.name %> 
    </li>
    <li>
      <b>Shout:</b> <%= s.body %>
    </li>
    <li>
        <% s.comments.each do |c| %>
          <li class="comment">
            <%= c.body %>
          </li>
        <% end %>
    </li>
    <%= link_to "Comment", new_shout_comment_path(s) %>
    <%= link_to "Edit Shout", edit_shout_path(s) %>
    <%= link_to "Delete Shout", shout_path(s), :method => :delete %>
  </ul>
<% end %>

</div>
<div id="button">
  <button>
    <%= link_to "Add Shout", new_shout_path %>
  </button>
</div>

app/views/shouts/new.html.erb
<div id="shout-form">
  <%= form_for @shout do |form| %>
    <%= form.error_messages %>
    <p>
      <%= form.label      :name %>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label     :body %>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>  
  <% end %>
</div>